version: '3.9'
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag_postgres
    restart: always
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - rag_pgdata:/var/lib/postgresql/data

volumes:
  rag_pgdata:
